# Generated by Django 4.2.19 on 2025-05-12 03:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SearchEngine",
            fields=[
                (
                    "name",
                    models.CharField(max_length=15, primary_key=True, serialize=False),
                ),
                ("baseUrl", models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name="SearchTermMapping",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("searchTerm", models.CharField(max_length=150)),
                ("time_searched", models.DateTimeField()),
                (
                    "searchEngineName",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="searchFilter.searchengine",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SearchUrls",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("url", models.CharField(max_length=500)),
                ("desc", models.CharField(max_length=500)),
                ("title", models.CharField(max_length=500)),
                ("ad_promo", models.BooleanField()),
                ("data_scrape_time", models.DateTimeField(null=True)),
                (
                    "searchTermId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="searchFilter.searchtermmapping",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UrlData",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("count_of_appearance", models.BigIntegerField()),
                ("html_data", models.TextField()),
                (
                    "searchUrls",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="searchFilter.searchurls",
                    ),
                ),
            ],
        ),
    ]
